kind: pipeline
name: default

steps:
  - name: build-rc
    image: docker/compose:1.24.0
    commands:
      - cd deploy/rc
      - touch .env.private
      - echo  $PASSWORD | docker login -u $USERNAME --password-stdin registry.urbanscheduler.ml
      - docker-compose build
      - docker-compose push
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      HERE_APP_ID:
        from_secret: HERE_APP_ID
      HERE_APP_CODE:
        from_secret: HERE_APP_CODE
    when:
      branch: rc
      event: push

  - name: deploy-rc
    image: appleboy/drone-ssh
    settings:
      host: rc.urbanscheduler.ml
      username: cloud-user
      port: 22
      ssh_key:
        from_secret: ssh_key
      script:
        - cd ~/urban-scheduler/deploy/rc
        - docker-compose pull
        - docker-compose up -d
        - docker-compose exec -T app bash -c "python -m unittest tests.test"
    when:
      branch: rc
      event: push

  - name: global-tests
    image: registry.urbanscheduler.ml/app:rc
    commands:
      - sleep 30 # Wait while certs are renewed
      - cd global_tests
      - python -m unittest
    when:
      branch: rc
      event: push

  - name: build-prod
    image: docker/compose:1.24.0
    commands:
      - cd deploy/prod
      - echo  $PASSWORD | docker login -u $USERNAME --password-stdin registry.urbanscheduler.ml
      - touch .env.private
      - docker-compose build
      - docker-compose push
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      HERE_APP_ID:
        from_secret: HERE_APP_ID
      HERE_APP_CODE:
        from_secret: HERE_APP_CODE
    when:
      branch: master
      event: push

  - name: deploy-prod
    image: appleboy/drone-ssh
    settings:
      host: urbanscheduler.ml
      username: omrigan
      port: 22
      ssh_key:
        from_secret: ssh_key
      script:
        - cd ~/urban-scheduler/deploy/prod
        - docker-compose pull
        - docker-compose up -d
    when:
      branch: master
      event: push

image_pull_secrets:
  - dockerconfigjson


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
