kind: pipeline
name: default

steps:
  - name: build
    image: docker/compose:1.24.0
    commands:
      - cd deploy/prod
      - echo  $PASSWORD | docker login -u $USERNAME --password-stdin registry.urbanscheduler.ml
      - docker-compose build
      - docker-compose push
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: urbanscheduler.ml
      username: omrigan
      port: 22
      key_path: key
      script:
        - cd ~/urban-scheduler/deploy/prod
        - docker-compose pull
        - docker-compose up -d
    volumes:
      - name: ssh_key
        path: key
    when:
      branch: master
      event: push1

image_pull_secrets:
  - dockerconfigjson


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

  - name: ssh_key
    host:
      path: .ssh/kolobok-devservices
