kind: pipeline
name: default

steps:
  - name: build
    image: docker/compose:1.24.0
    commands:
      - cd deploy/prod
      - docker-compose build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: deploy
    image: appleboy/drone-ssh
    host: urbanscheduler.ml
    username: cloud-user
    port: 22
    secrets: [ ssh_key ]
    script:
      - cd ~/urban-scheduler/deploy/prod
      - docker-compose pull
      - docker-compose up -d
    when:
      branch: master
      event: push




volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
