kind: pipeline
name: default

steps:
  - name: build
    image: docker/compose:1.24.0
    commands:
      - cd deploy/prod
      - docker version
#      - export
#      - echo  $PASSWORD | docker login -u $USERNAME --password-stdin registry.urbanscheduler.ml
      - docker-compose build
      - docker-compose push
    volumes:
      - name: docker
        path: /var/run/docker.sock
#    environment:
#      USERNAME:
#        from_secret: registry_username
#      PASSWORD:
#        from_secret: registry_password


  - name: deploy
    image: appleboy/drone-ssh
    host: urbanscheduler.ml
    username: cloud-user
    port: 22
    secrets: [ ssh_key ]
    script:
      - cd ~/urban-scheduler/deploy/prod
      - docker-compose pull
      - docker-compose up -d
    when:
      branch: master
      event: push

image_pull_secrets:
  dockerloginjson


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
