kind: pipeline
name: default

steps:
- name: run
  image: docker/compose
  commands:
  - cd deploy/dev
  - docker-compose up
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: build-app
  image: docker
  commands:
  - cd app
  - docker build .
  volumes:
  - name: docker
    path: /var/run/docker.sock


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
