version: '3.4'

services: {
  osrm:{
    image: osrm/osrm-backend,
    command: osrm-routed --algorithm mld /data/osrm-final.osrm,
    volumes: ["../../data/osrm:/data",
              "../../data_raw/osm-files/osrm-final.osm.pbf:/data/osrm-final.osm.pbf:ro"],
    ports: ["5000:5000"]
  },
  mongo:{
    image: mongo,
    ports: ["27017:27017"],
    volumes:["../../data/mongo:/data/db",
             "../../data/mongo_backups:/mongo_backups",
             "../../data_raw/mongo_ready:/mongo_ready:ro"]
  },
  app: {
    image: "registry.urbanscheduler.ml/app:dev",
    build: ../../app,
    volumes: [
      "../../app:/app",
      "../../data_raw:/data_raw:ro",
    ],
    command: /start-dev.sh,
    ports: ["89:80"]
  },
  rustapp: {
    image: "registry.urbanscheduler.ml/rustapp:dev",
    build: {
      context: ../../rustapp,
      target: "build",
    },
    env_file: [.env.private],
    ports: ["90:80"],
    volumes: ["../../rustapp:/rustapp"],
    command: /rustapp/restart-on-filechange.sh
  },
  front: {
    image: "registry.urbanscheduler.ml/front:dev",
    build: {
      context: ../../front,
      target: "build"
    },
    ports: ["80:80"],
    volumes: ["../../front:/front"],
    command: npm start
  },
}


