version: '3'

services: {
  osrm:{
    container_name: osrm,
    image: osrm/osrm-backend,
    command: osrm-routed --algorithm mld /data/moscow.osrm,
    volumes: ["../../data/osrm:/data"],
    ports: ["5000:5000"]
  },
  mongo:{
    container_name: mongo,
    image: mongo,
    ports: ["27017:27017"],
    volumes:["../../data/mongo:/data/db"]
  },
  app: {
    container_name: app,
    image: registry.urbanscheduler.ml/app:dev,
    build: ../../app,
    volumes: [
      "../../app:/app",
      "../../data/raw_data:/data/raw_data",
      "../../data/osm-files:/data/osm-files"
    ],
    command: /start-dev.sh,
    ports: ["89:80"]
  },
  rustapp: {
    container_name: rustapp,
    image: registry.urbanscheduler.ml/rustapp:dev,
    build: ../../rustapp,
    ports: ["90:80"],
    volumes: ["../../rustapp:/rustapp"],
    target: build,
    command: /rustapp/restart-on-filechange.sh
  },
  front: {
    container_name: front,
    image: registry.urbanscheduler.ml/front:dev,
    build: ../../front,
    ports: ["80:80"],
    volumes: ["../../front:/front"],
    target: build,
    command: npm start
  },
}


