version: '3'

services: {
  osrm:{
    image: osrm/osrm-backend,
    command: osrm-routed --algorithm mld /data/moscow.osrm,
    volumes: ["../../data/osrm:/data"],
    expose: [5000]
  },
  mongo:{
    image: mongo,
    volumes:["../../data/mongo:/data/db"],
    expose: [27017]
  },
  app: {
    image: registry.urbanscheduler.ml/app,
    build: ../../app,
    expose: [80],
    environment: {
      VIRTUAL_HOST: api.urbanscheduler.ml,
      LETSENCRYPT_HOST: api.urbanscheduler.ml
    }
  },
  rustapp: {
    image: registry.urbanscheduler.ml/rustapp,
    command: /usr/local/bin/usrust,
    build: ../../rustapp,
  },
  front: {
    image: registry.urbanscheduler.ml/front,
    build: ../../front,
    expose: [80],
    environment: {
        VIRTUAL_HOST: urbanscheduler.ml,
        LETSENCRYPT_HOST: urbanscheduler.ml
    }
  },
}
networks:
  default:
    external:
      name: webproxy


