version: '3'

services: {
  osrm:{
    image: osrm/osrm-backend,
    command: osrm-routed --algorithm mld /data/moscow.osrm,
    volumes: ["../../data/osrm:/data"],
    expose: [5000]
  },
  mongo:{
    image: mongo,
    volumes:["../../data/mongo:/data/db"],
    expose: [27017]
  },
  app: {
    image: registry.urbanscheduler.ml/app,
    build: ../../app,
    ports: ["89:80"]
  },
  rustapp: {
    image: registry.urbanscheduler.ml/rustapp,
    build: ../../rustapp,
  },
  front: {
    image: registry.urbanscheduler.ml/front,
    build: ../../front,
    ports: ["80:80"],
  },
}


