version: '3'

services: {
  osrm:{
    image: osrm/osrm-backend,
    command: osrm-routed --algorithm mld /data/osrm-final.osrm,
    volumes: ["../../data/osrm:/data",
              "../../data_raw/osm-files/osrm-final.osm.pbf:/data/osrm-final.osm.pbf:ro"],
    expose: [5000]
  },
  mongo:{
    image: mongo,
    volumes:["../../data/mongo:/data/db",
             "../../data/mongo_backups:/mongo_backups",
             "../../data_raw/mongo_ready:/mongo_ready:ro"],
    expose: [27017]
  },
  app: {
    image: "registry.urbanscheduler.ml/app:rc",
    build: ../../app,
    expose: [80],
    depends_on: [mongo],
    environment: {
      VIRTUAL_HOST: api.rc.urbanscheduler.ml,
      LETSENCRYPT_HOST: api.rc.urbanscheduler.ml
    },
    volumes: [
      "../../data_raw:/data_raw:ro",
    ],
  },
  rustapp: {
    image: "registry.urbanscheduler.ml/rustapp:rc",
    build: {
      context: ../../rustapp,
      args: ["HERE_APP_CODE", "HERE_APP_ID"]
    },
    env_file: [.env.private]
  },
  front: {
    image: "registry.urbanscheduler.ml/front:rc",
    build:{
      context: ../../front,
      dockerfile: Dockerfile-rc
    },
    expose: [80],
    environment: {
      VIRTUAL_HOST: rc.urbanscheduler.ml,
      LETSENCRYPT_HOST: rc.urbanscheduler.ml
    }
  },
}
networks:
  default:
    external:
      name: webproxy


