FROM node as build

WORKDIR /front
ADD . /front

RUN npm install

RUN export REACT_APP_TITLE="RC Urban Scheduler"
RUN export REACT_APP_URL="https://api.rc.urbanscheduler.ml"

RUN npm run build

FROM nginx:latest

COPY --from=build /front/build/ /usr/share/nginx/html/